<?php

/**
 * This is the model base class for the table "producto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Producto".
 *
 * Columns in table "producto" available as properties of the model,
 * followed by relations of table "producto" available as properties of the model.
 *
 * @property integer $id
 * @property integer $local_id
 * @property integer $categoria_id
 * @property string $nombre
 * @property string $precio
 * @property string $detalle
 * @property string $foto
 *
 * @property Local $local
 * @property Categoria $categoria
 */
abstract class BaseProducto extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'producto';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Producto|Productos', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('local_id, categoria_id', 'numerical', 'integerOnly'=>true),
			array('nombre, precio, foto', 'length', 'max'=>45),
			array('detalle', 'length', 'max'=>100),
			array('local_id, categoria_id, nombre, precio, detalle, foto', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, local_id, categoria_id, nombre, precio, detalle, foto', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'local' => array(self::BELONGS_TO, 'Local', 'local_id'),
			'categoria' => array(self::BELONGS_TO, 'Categoria', 'categoria_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'local_id' => null,
			'categoria_id' => null,
			'nombre' => Yii::t('app', 'Nombre'),
			'precio' => Yii::t('app', 'Precio'),
			'detalle' => Yii::t('app', 'Detalle'),
			'foto' => Yii::t('app', 'Foto'),
			'local' => null,
			'categoria' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('local_id', $this->local_id);
		$criteria->compare('categoria_id', $this->categoria_id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('precio', $this->precio, true);
		$criteria->compare('detalle', $this->detalle, true);
		$criteria->compare('foto', $this->foto, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}