<?php

/**
 * This is the model base class for the table "local".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Local".
 *
 * Columns in table "local" available as properties of the model,
 * followed by relations of table "local" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $nombre
 * @property string $direccion
 * @property string $fono
 * @property string $resumen
 * @property string $latitud
 * @property string $longitud
 * @property string $foto
 *
 * @property User $user
 * @property Producto[] $productos
 * @property UserPlan[] $userPlans
 */
abstract class BaseLocal extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'local';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Local|Locals', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('user_id', 'required'),
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('nombre, fono, foto', 'length', 'max'=>45),
			array('direccion', 'length', 'max'=>100),
			array('resumen', 'length', 'max'=>200),
			array('latitud, longitud', 'length', 'max'=>18),
			array('nombre, direccion, fono, resumen, latitud, longitud, foto', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, nombre, direccion, fono, resumen, latitud, longitud, foto', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'productos' => array(self::HAS_MANY, 'Producto', 'local_id'),
			'userPlans' => array(self::HAS_MANY, 'UserPlan', 'local_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'nombre' => Yii::t('app', 'Nombre'),
			'direccion' => Yii::t('app', 'Direccion'),
			'fono' => Yii::t('app', 'Fono'),
			'resumen' => Yii::t('app', 'Resumen'),
			'latitud' => Yii::t('app', 'Latitud'),
			'longitud' => Yii::t('app', 'Longitud'),
			'foto' => Yii::t('app', 'Foto'),
			'user' => null,
			'productos' => null,
			'userPlans' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('direccion', $this->direccion, true);
		$criteria->compare('fono', $this->fono, true);
		$criteria->compare('resumen', $this->resumen, true);
		$criteria->compare('latitud', $this->latitud, true);
		$criteria->compare('longitud', $this->longitud, true);
		$criteria->compare('foto', $this->foto, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}